const COLUMN_CONFIG = {
    "bank-accounts": {
      bat_ID: { label: "ID", showInTable: true, showInForm: false },
      bat_UserID: { label: "User ID", showInTable: false, showInForm: false },
      bat_Number: { label: "Account Number", showInTable: true, showInForm: true },
      bat_Type: { label: "Account Type", showInTable: true, showInForm: true },
      bat_Bank: { label: "Bank", showInTable: true, showInForm: true },
      bat_CreatedAt: { label: "Created At", showInTable: true, showInForm: false, type: "date" },
      bat_UpdatedAt: { label: "Updated At", showInTable: true, showInForm: false, type: "date" },
    },
    "balances": {
    blc_ID: { label: "ID", showInTable: true, showInForm: false },
    BankAccountDisplay: { label: "Bank Account", showInTable: true, showInForm: false },
    blc_UserID: { label: "User ID", showInTable: false, showInForm: false },
    blc_BankAccountID: { label: "Bank Account", showInTable: false, showInForm: true, type: "select",optionsSource: "bank-accounts" },    
    blc_DatePeriod: { label: "Period Date", showInTable: true, showInForm: true, type: "date" },
    blc_IniAmount: { label: "Initial Amount", showInTable: true, showInForm: true, type: "currency" },
    blc_FinalAmount: { label: "Final Amount", showInTable: true, showInForm: true, type: "currency" },
    blc_IsClosed: { label: "Closed", showInTable: false, showInForm: true },
    blc_CreatedAt: { label: "Created At", showInTable: true, showInForm: false, type: "date" },
    blc_UpdatedAt: { label: "Updated At", showInTable: true, showInForm: false,type: "date" },
  },
  "incomes": {
    inc_ID: { label: "ID", showInTable: true, showInForm: false },
    inc_UserID: { label: "User ID", showInTable: false, showInForm: false },
    inc_BankAccountID: { label: "Bank Account", showInTable: false, showInForm: true, type: "select",optionsSource: "bank-accounts" },
    BankAccountDisplay: { label: "Bank Account", showInTable: true, showInForm: false },
    inc_Amount: { label: "Amount", showInTable: true, showInForm: true, type: "currency" },
    inc_Type: { label: "Type", showInTable: true, showInForm: true },
    inc_Desc: { label: "Description", showInTable: true, showInForm: true },
    inc_CreatedAt: { label: "Created At", showInTable: true, showInForm: false,type: "date" },
    inc_UpdatedAt: { label: "Updated At", showInTable: false, showInForm: false,type: "date" },
  },
  "outgoins": {
    otg_ID: { label: "ID", showInTable: true, showInForm: false },
    otg_UserID: { label: "User ID", showInTable: false, showInForm: false },
    otg_BankAccountID: { label: "Bank Account", showInTable: false, showInForm: true, type: "select",optionsSource: "bank-accounts" },
    BankAccountDisplay: { label: "Bank Account", showInTable: true, showInForm: false },
    otg_Amount: { label: "Amount", showInTable: true, showInForm: true, type: "currency" },
    otg_Type: { label: "Type", showInTable: true, showInForm: true },
    otg_Desc: { label: "Description", showInTable: true, showInForm: true },
    otg_CreatedAt: { label: "Created At", showInTable: true, showInForm: false,type: "date" },
    otg_UpdatedAt: { label: "Updated At", showInTable: false, showInForm: false ,type: "date"},
  },
  "transfers": {
    trf_ID: { label: "ID", showInTable: true, showInForm: false },
    trf_UserID: { label: "User ID", showInTable: false, showInForm: false },
    trf_FromAccountID: { label: "From Account", showInTable: false, showInForm: true, type: "select", optionsSource: "bank-accounts" },
    FromAccountDisplay: { label: "From Account", showInTable: true, showInForm: false },
    trf_ToAccountID: { label: "To Account", showInTable: false, showInForm: true, type: "select", optionsSource: "bank-accounts" },
    ToAccountDisplay: { label: "To Account", showInTable: true, showInForm: false },
    trf_Amount: { label: "Amount", showInTable: true, showInForm: true, type: "currency" },
    trf_Description: { label: "Description", showInTable: true, showInForm: true },
    trf_CreatedAt: { label: "Created At", showInTable: true, showInForm: false, type: "date" },
  },
    
  };
  
  export default COLUMN_CONFIG;